apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.alb.configMapName | default "alb-nginx-html" }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
data:
  default.conf: |
{{ tpl (include "alb.defaultConf" .) . | indent 4 }}
