apiVersion: v1
kind: Service
metadata:
  name: {{ include "alertmanager.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "alertmanager.fullname" . }}
spec:
  selector:
    app: {{ include "alertmanager.fullname" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.alertmanager.service.port }}
      targetPort: {{ .Values.alertmanager.service.targetPort }}
  type: {{ .Values.alertmanager.service.type }}
