apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "alertmanager.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "alertmanager.fullname" . }}
spec:
  replicas: {{ .Values.alertmanager.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "alertmanager.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "alertmanager.fullname" . }}
    spec:
      containers:
        - name: alertmanager
          image: "{{ .Values.alertmanager.image.repository }}:{{ .Values.alertmanager.image.tag }}"
          imagePullPolicy: {{ .Values.alertmanager.image.pullPolicy }}
          args:
            - "--config.file=/etc/alertmanager/alertmanager.yml"
          ports:
            - containerPort: {{ .Values.alertmanager.containerPort }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/alertmanager
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.alertmanager.configMapName }}
