apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.alertRules.configMapName }}
  namespace: {{ .Release.Namespace }}
data:
  {{ .Values.alertRules.fileName }}: |
    groups:
{{ toYaml .Values.alertRules.rules.groups | indent 6 }}
