apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apiGateway.fullnameOverride | default "api-gateway" }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  type: {{ .Values.apiGateway.service.type | default "NodePort" }}
  selector:
    app: {{ .Values.apiGateway.fullnameOverride | default "api-gateway" }}
  ports:
    - port: {{ .Values.apiGateway.service.port | default 8081 }}
      targetPort: {{ .Values.apiGateway.service.targetPort | default 8081 }}
      {{- if eq (.Values.apiGateway.service.type | default "NodePort") "NodePort" }}
      nodePort: {{ .Values.apiGateway.service.nodePort | default 30081 }}
      {{- end }}
