apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend-service.fullname" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  type: {{ .Values.backendService.service.type }}
  selector:
    app: {{ include "backend-service.name" . }}
  ports:
    - port: {{ .Values.backendService.service.port }}
      targetPort: {{ .Values.backendService.service.targetPort }}
