{{- if .Values.backendService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend-service.fullname" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    app: {{ include "backend-service.name" . }}
spec:
  replicas: {{ .Values.backendService.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "backend-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "backend-service.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.backendService.image.repository }}:{{ .Values.backendService.image.tag }}"
          imagePullPolicy: {{ .Values.backendService.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backendService.containerPort }}
          env:
            - name: DATABASE_URL
              value: "{{ .Values.backendService.databaseUrl }}"
            - name: REDIS_HOST
              value: "{{ .Values.backendService.redis.host }}"
            - name: REDIS_PORT
              value: "{{ .Values.backendService.redis.port }}"
              restartPolicy: Always
{{- end }}