{{- if .Values.backendLandRegistry.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend-landregistry.fullname" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    app: {{ include "backend-landregistry.name" . }}
spec:
  replicas: {{ .Values.backendLandRegistry.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "backend-landregistry.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "backend-landregistry.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.backendLandRegistry.image.repository }}:{{ .Values.backendLandRegistry.image.tag }}"
          imagePullPolicy: {{ .Values.backendLandRegistry.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backendLandRegistry.containerPort }}
          env:
            - name: DATABASE_URL
              value: "{{ .Values.backendLandRegistry.databaseUrl }}"
            - name: REDIS_HOST
              value: "{{ .Values.backendLandRegistry.redis.host }}"
            - name: REDIS_PORT
              value: "{{ .Values.backendLandRegistry.redis.port }}"
      restartPolicy: Always
{{- end }}
