apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "frontend.fullname" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    app: {{ include "frontend.fullname" . }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "frontend.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "frontend.fullname" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
          imagePullPolicy: {{ .Values.frontend.image.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
              readOnly: true
      volumes:
        - name: html-volume
          configMap:
            name: {{ .Values.frontend.configMapName }}
