apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana.datasource.ConfigMapName" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    grafana_datasource: "1"
data:
  prometheus-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://{{ include "prometheus.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.prometheus.service.port }}
        isDefault: true
