apiVersion: v1
kind: Service
metadata:
  name: {{ include "grafana.fullname" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    app: {{ include "grafana.name" . }}
spec:
  type: {{ .Values.grafana.service.type }}
  selector:
    app: {{ include "grafana.name" . }}
  ports:
    - name: http
      port: {{ .Values.grafana.service.port }}
      targetPort: {{ .Values.grafana.service.targetPort }}
      protocol: TCP
      {{- if and (eq .Values.grafana.service.type "NodePort") (.Values.grafana.service.nodePort) }}
      nodePort: {{ .Values.grafana.service.nodePort }}
      {{- end }}
