apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lambda-producer.fullname" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    app: {{ include "lambda-producer.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "lambda-producer.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "lambda-producer.name" . }}
    spec:
      restartPolicy: Always

      # 🛠️ Moved initContainers here
      initContainers:
        - name: wait-for-rabbitmq
          image: busybox
          command:
            - sh
            - -c
            - |
              echo "Waiting for RabbitMQ...";
              until nc -z rabbitmq-landregistry.helm-app.svc.cluster.local 5672; do
                echo "RabbitMQ not ready. Sleeping...";
                sleep 3;
              done
              echo "RabbitMQ is ready!"

      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.lambdaProducer.image.repository }}:{{ .Values.lambdaProducer.image.tag }}"
          imagePullPolicy: {{ .Values.lambdaProducer.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.lambdaProducer.containerPort }}

          env:
{{- with .Values.lambdaProducer.env }}
      {{- toYaml . | nindent 12 }}
{{- end }}

