apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "consumer-landregistry.fullname" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    app: {{ include "consumer-landregistry.name" . }}
spec:
  replicas: {{ .Values.consumerLandRegistry.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "consumer-landregistry.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "consumer-landregistry.name" . }}
    spec:
      restartPolicy: Always

      initContainers:
        - name: wait-for-rabbitmq
          image: busybox
          command:
            - sh
            - -c
            - |
              echo "Waiting for RabbitMQ...";
              until nc -z rabbitmq-landregistry.helm-app.svc.cluster.local 5672; do
                echo "RabbitMQ not ready. Sleeping...";
                sleep 3;
              done
              echo "RabbitMQ is ready!"

      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.consumerLandRegistry.image.repository }}:{{ .Values.consumerLandRegistry.image.tag }}"
          imagePullPolicy: {{ .Values.consumerLandRegistry.image.pullPolicy }}
          env:
            - name: RABBITMQ_URL
              value: "{{ .Values.consumerLandRegistry.rabbitmqUrl }}"
          ports:
            - containerPort: {{ .Values.consumerLandRegistry.containerPort }}
