apiVersion: v1
kind: Service
metadata:
  name: {{ include "consumer-landregistry.fullname" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    app: {{ include "consumer-landregistry.name" . }}
spec:
  type: {{ .Values.consumerLandRegistry.service.type }}
  selector:
    app: {{ include "consumer-landregistry.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.consumerLandRegistry.service.port }}
      targetPort: {{ .Values.consumerLandRegistry.service.targetPort }}
