apiVersion: v1
kind: Service
metadata:
  name: {{ default "postgres-landregistry" (include "postgres-landregistry.fullname" .) }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    app: {{ include "postgres-landregistry.name" . }}
spec:
  type: {{ .Values.postgresLandRegistry.service.type }}
  selector:
    app: {{ include "postgres-landregistry.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.postgresLandRegistry.service.port }}
      targetPort: {{ .Values.postgresLandRegistry.service.targetPort }}
