apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.prometheus.rbac.clusterRoleBindingName }}
subjects:
  - kind: ServiceAccount
    name: {{ required "Missing value: prometheus.serviceAccount.name" .Values.prometheus.serviceAccount.name }}
    namespace: {{ .Values.namespace | default .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.prometheus.rbac.clusterRoleName }}
  apiGroup: rbac.authorization.k8s.io
