{{- if .Values.alb }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.alb.tlsSecretName | default "alb-nginx-tls" }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get "files/tls.crt" | b64enc }}
  tls.key: {{ .Files.Get "files/tls.key" | b64enc }}
{{- end }}